"""create users table

Revision ID: 42c43a58d809
Revises:
Create Date: 2026-06-30 17:20:14.792976

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "42c43a58d809"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
